package db

import (
	"database/sql"
	"log"
	"os"
	"testing"

	_ "github.com/lib/pq"
)

const (
	dbDriver = "postgres"
	dbSource = "postgresql://root:secret@localhost:5432/simple_bank?sslmode=disable"
)

// Queries is the struct that holds the db connection
// which is generated by sqlc
var testQueries *Queries
var testDB *sql.DB

func TestMain(m *testing.M) {
	var err error
	// connect to db
	testDB, err = sql.Open(dbDriver, dbSource)
	if err != nil {
		log.Fatal("cannot connect to db:", err)
	}

	// create testQueries
	testQueries = New(testDB)

	os.Exit(m.Run())
}
